"""Admin entry point for official government information.

WHY THIS IS A HUMAN-ENTERED FEED
--------------------------------
IMD, CWC and state disaster portals publish HTML pages and PDFs, not stable
JSON APIs. A scraper against them breaks on any layout change, and it breaks
SILENTLY — which for a flood warning is worse than never having built it,
because by then the farmer has learned to rely on it.

So an admin enters each advisory, and the model enforces what matters:

  * source_name and source_url are REQUIRED. A compensation figure with no
    link cannot be used by a farmer standing in a government office.
  * amount is a number the admin copies from the notice. Nothing computes or
    infers it, and no LLM is involved anywhere in this path.

EXTENSIBILITY
-------------
`ingested_by` marks the origin: 'admin' today, 'api:imd' or 'api:cwc' when a
real feed exists. A future ingester writes rows in this same shape and the
rule engine, the alerts and the UI all continue unchanged.
"""

import logging
from datetime import datetime
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field, HttpUrl
from sqlalchemy.orm import Session

from app.core.security import get_current_user, require_admin
from app.database.db import get_db
from app.models.models import ExternalAdvisory, User

log = logging.getLogger("agri.api.advisory")

advisory_router = APIRouter(prefix="/api/advisories", tags=["advisories"])

VALID_KINDS = ("scheme", "flood", "disaster", "compensation", "supplies")


class AdvisoryIn(BaseModel):
    kind: str
    title: str = Field(min_length=3)
    summary: str = ""
    action: str = ""

    state: str = ""
    districts: List[str] = []
    crops: List[str] = []

    amount: Optional[float] = Field(None, ge=0)
    amount_unit: str = ""
    amount_note: str = ""

    # Not optional. This table exists to make claims traceable.
    source_name: str = Field(min_length=2)
    source_url: HttpUrl
    published_on: Optional[str] = None

    priority: str = "MEDIUM"
    severity: str = "INFO"
    expires_on: Optional[str] = None


def _shape(a: ExternalAdvisory) -> dict:
    return {
        "id": a.id, "kind": a.kind, "title": a.title, "summary": a.summary,
        "action": a.action, "state": a.state, "districts": a.districts or [],
        "crops": a.crops or [], "amount": a.amount,
        "amount_unit": a.amount_unit, "amount_note": a.amount_note,
        "source": {"name": a.source_name, "url": a.source_url,
                   "published_on": (a.published_on.date().isoformat()
                                    if a.published_on else None)},
        "priority": a.priority, "severity": a.severity, "active": a.active,
        "expires_at": a.expires_at.isoformat() if a.expires_at else None,
        "ingested_by": a.ingested_by,
        "created_at": a.created_at.isoformat() if a.created_at else None,
    }


@advisory_router.get("")
def list_advisories(kind: str = "", active_only: bool = True,
                    user: User = Depends(get_current_user),
                    db: Session = Depends(get_db)):
    """Official advisories on record. Readable by any farmer.

    Deliberately not admin-only: a farmer should be able to see the full list
    of announcements with their sources, not only the ones matched to them.
    """
    q = db.query(ExternalAdvisory)
    if active_only:
        q = q.filter(ExternalAdvisory.active == True)       # noqa: E712
    if kind:
        q = q.filter(ExternalAdvisory.kind == kind)
    rows = q.order_by(ExternalAdvisory.created_at.desc()).limit(200).all()
    return {"count": len(rows), "advisories": [_shape(a) for a in rows],
            "note": ("Entered from official sources by an administrator. Each "
                     "carries the source link and publication date. Nothing "
                     "here is generated by AI.")}


@advisory_router.post("")
def create_advisory(data: AdvisoryIn, admin: User = Depends(require_admin),
                    db: Session = Depends(get_db)):
    """Record one official advisory. Admin only."""
    kind = data.kind.strip().lower()
    if kind not in VALID_KINDS:
        raise HTTPException(
            400, f"kind must be one of: {', '.join(VALID_KINDS)}")

    if kind == "compensation" and data.amount is None:
        raise HTTPException(
            400, "A compensation advisory must carry the announced amount. "
                 "If no figure has been announced, record it as a 'scheme' "
                 "instead of leaving the amount blank.")

    def _parse(value, label):
        if not value:
            return None
        try:
            return datetime.fromisoformat(value)
        except ValueError:
            raise HTTPException(400, f"{label} must be ISO format yyyy-mm-dd")

    row = ExternalAdvisory(
        kind=kind, title=data.title.strip(), summary=data.summary,
        action=data.action, state=data.state.strip(),
        districts=[d.strip() for d in data.districts if d.strip()],
        crops=[c.strip().lower() for c in data.crops if c.strip()],
        amount=data.amount, amount_unit=data.amount_unit,
        amount_note=data.amount_note,
        source_name=data.source_name.strip(), source_url=str(data.source_url),
        published_on=_parse(data.published_on, "published_on"),
        priority=data.priority.upper(), severity=data.severity.upper(),
        expires_at=_parse(data.expires_on, "expires_on"),
        ingested_by="admin", created_by=admin.id, active=True,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    log.info("advisory recorded: %s / %s by admin %s", kind, row.title, admin.id)
    return _shape(row)


@advisory_router.patch("/{advisory_id}/deactivate")
def deactivate_advisory(advisory_id: int, admin: User = Depends(require_admin),
                        db: Session = Depends(get_db)):
    """Retire an advisory without deleting it, so the record survives."""
    row = db.query(ExternalAdvisory).filter(
        ExternalAdvisory.id == advisory_id).first()
    if row is None:
        raise HTTPException(404, "Advisory not found.")
    row.active = False
    db.commit()
    return {"status": "deactivated", "id": advisory_id}
