"""Government funding & scheme intelligence API.

All endpoints are admin-only (require_admin) — this is the government
officer's view, never exposed to farmer accounts. Every response is built
from real rows in SchemeBudget / StateFunding / DistrictFunding (see
app/services/government_funding.py for the exact provenance rules), joined
with the platform's real operational data (admin_intel.py) — never
generated by an LLM.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database.db import get_db
from app.models.models import User, Scheme
from app.core.security import require_admin
from app.services import government_funding as gf
from app.services import mandi_price
from app.services import pest_outbreak

funding_router = APIRouter(prefix="/api/admin/funding", tags=["government-funding"])


@funding_router.get("/overview")
def funding_overview(state: str = "India", admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.funding_overview(db, state)


@funding_router.get("/schemes")
def scheme_list(financial_year: str = gf.CURRENT_FY,
               admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.scheme_budget_list(db, financial_year)


@funding_router.get("/schemes/{scheme_id}")
def scheme_detail(scheme_id: int, financial_year: str = gf.CURRENT_FY,
                  admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    detail = gf.scheme_detail(db, scheme_id, financial_year)
    if not detail:
        raise HTTPException(404, "Scheme not found")
    return detail


@funding_router.get("/states")
def state_funding(financial_year: str = gf.CURRENT_FY, scheme_id: int = 0,
                  admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.state_funding_list(db, financial_year, scheme_id or None)


@funding_router.get("/districts")
def district_funding(state: str = "Madhya Pradesh", financial_year: str = gf.CURRENT_FY,
                     scheme_id: int = 0, sort_by: str = "allocated",
                     admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.district_funding_list(db, state, financial_year, scheme_id or None, sort_by)


@funding_router.get("/districts/{district}")
def district_detail(district: str, state: str = "Madhya Pradesh", financial_year: str = gf.CURRENT_FY,
                    admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.district_funding_detail(db, state, district, financial_year)


@funding_router.get("/coverage-gap")
def coverage_gap(state: str = "Madhya Pradesh", financial_year: str = gf.CURRENT_FY,
                 admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.coverage_gap_analysis(db, state, financial_year)


@funding_router.get("/scheme-eligibility")
def scheme_eligibility(state: str = "Madhya Pradesh", district: str = "",
                       admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    """Section: 'which schemes might be applicable for which state/district
    farmers?' — see government_funding.predict_scheme_eligibility for the
    exact (deterministic, real-profile-based) method."""
    return gf.predict_scheme_eligibility(db, state, district)


@funding_router.get("/financial-alerts")
def financial_alerts(state: str = "Madhya Pradesh", financial_year: str = gf.CURRENT_FY,
                     admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.financial_alerts(db, state, financial_year)


@funding_router.get("/district-ranking")
def district_ranking(state: str = "Madhya Pradesh", financial_year: str = gf.CURRENT_FY,
                     admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.district_ranking(db, state, financial_year)


@funding_router.get("/what-changed")
def what_changed(state: str = "", admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.what_changed(db, state)


@funding_router.get("/crop-health-heatmap")
def crop_health_heatmap(state: str = "Madhya Pradesh",
                        admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.crop_health_heatmap(db, state)


@funding_router.get("/satellite/{district}")
def satellite_summary(district: str, state: str = "Madhya Pradesh",
                      admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    return gf.satellite_district_summary(db, state, district)


@funding_router.get("/market-insight")
async def market_government_insight(state: str = "Madhya Pradesh", crop: str = "",
                                    admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    """Section 18 — live mandi price (existing AGMARKNET-backed service,
    never invented here) combined with the platform's own real listing
    trend, to surface a plain-language market/government-action insight.
    """
    from app.services import admin_intel
    detail = admin_intel.state_detail(db, state)
    increasing = detail["crops"]["increasing"]
    declining = detail["crops"]["declining"]

    insights = []
    for c in (declining or [])[:5]:
        if c in (increasing or []):
            continue
        try:
            raw = await mandi_price.fetch_prices(state=state, commodity=mandi_price.canonical_commodity(c), limit=20)
            summary = mandi_price.summarise(raw, c)
        except Exception:
            summary = {"status": "unavailable"}
        price_note = ""
        if summary.get("status") == "ok" and summary.get("modal_avg"):
            price_note = (f" Current modal mandi price: ₹{summary['modal_avg']}/quintal "
                         f"(range ₹{summary['modal_min']}–₹{summary['modal_max']}, "
                         f"{summary['markets_reporting']} market(s) reporting).")
        insights.append({
            "crop": c, "signal": "listings declining while still commonly grown",
            "market_price_note": price_note or "Live mandi price unavailable right now.",
            "possible_action": "Review market linkage / procurement support for this crop.",
        })
    for c in (increasing or [])[:5]:
        insights.append({
            "crop": c, "signal": "listings increasing (rising marketplace supply)",
            "market_price_note": "Monitor mandi price for potential oversupply softening.",
            "possible_action": "Watch for price decline as supply grows; consider storage/processing linkage.",
        })
    return {"state": state, "insights": insights,
           "note": "Trend is from this platform's own marketplace listings (a real but small "
                   "signal, not official production statistics); prices are live AGMARKNET data "
                   "via the existing market service, never invented."}


@funding_router.get("/report-brief")
def report_brief(state: str = "Madhya Pradesh", financial_year: str = gf.CURRENT_FY,
                 admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    """Section 25 — assembles the one-page government brief from the SAME
    functions the dashboard tabs use (never a separate/parallel computation
    that could drift out of sync). The frontend renders this as a printable
    page; there is no server-side PDF library in this project, so 'Export
    PDF' uses the browser's native print-to-PDF rather than adding a new
    dependency — see the report route in the frontend for the exact flow.
    """
    from app.services import admin_intel
    from datetime import datetime as dt

    overview = gf.funding_overview(db, state)
    schemes = gf.scheme_budget_list(db, financial_year)
    ranking = gf.district_ranking(db, state, financial_year)
    alerts = gf.financial_alerts(db, state, financial_year)
    priority = admin_intel.priority_alerts(db)
    heatmap = gf.crop_health_heatmap(db, state)
    changed = gf.what_changed(db, state)

    return {
        "generated_at": dt.utcnow().isoformat(),
        "title": f"{state} Agriculture Situation Brief — {dt.utcnow().strftime('%B %Y')}",
        "region": state, "financial_year": financial_year,
        "funding": overview,
        "scheme_performance": schemes[:8],
        "priority_districts": ranking[:5],
        "financial_alerts": alerts[:8],
        "operational_alerts": priority[:8],
        "crop_health": [d for d in heatmap if d["severity"] != "NONE"][:8],
        "what_changed": changed,
    }


# ---------- scheme -> state -> district drilldown convenience ----------

@funding_router.get("/schemes/{scheme_id}/states/{state}/districts")
def scheme_state_districts(scheme_id: int, state: str, financial_year: str = gf.CURRENT_FY,
                           admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    """Section 10's exact drill path: Scheme -> State -> District rows for
    that one scheme, so the frontend doesn't need to filter client-side."""
    scheme = db.query(Scheme).filter(Scheme.id == scheme_id).first()
    if not scheme:
        raise HTTPException(404, "Scheme not found")
    return gf.district_funding_list(db, state, financial_year, scheme_id, "allocated")


# ---------- pest outbreak scenario: detect -> AI-draft report -> PDF-ready ----------

@funding_router.post("/scenario/pest-outbreak")
async def scenario_pest_outbreak(state: str, district: str = "", pest_name: str = "",
                                 admin: User = Depends(require_admin), db: Session = Depends(get_db)):
    """The Scenario Simulator's '10+ farmers report the same pest' button.
    Runs the full agentic pipeline server-side, no human editing step:
      1. detect_outbreak (real DB query — the "tool")
      2. draft_report (LLM phrases those facts into an official report)
    Returns the complete report; the frontend renders it as a printable
    page (see GovernmentBrief.tsx's approach — no server-side PDF library
    in this project, so 'download PDF' uses the browser's print-to-PDF).
    """
    scenario = pest_outbreak.build_outbreak_scenario(db, state, district, pest_name)
    if not scenario["found"]:
        return {"found": False, "reason": scenario["reason"]}
    report = await pest_outbreak.draft_report(db, scenario)
    return {"found": True, **report}
